/**
 * UNSPSC (Código Estándar de Productos y Servicios de Naciones Unidas) labels used by
 * SECOP. Codes are published as "V1.43233200": segment = first 2 digits, family = 4.
 */
export const UNSPSC_SEGMENT_LABELS: Readonly<Record<string, string>> = {
  '10': 'Material vivo animal y vegetal',
  '11': 'Material mineral, textil y vegetal',
  '12': 'Material químico',
  '13': 'Resinas, caucho, espumas y elastómeros',
  '14': 'Materiales de papel',
  '15': 'Combustibles y lubricantes',
  '20': 'Maquinaria de minería y perforación',
  '21': 'Maquinaria agrícola',
  '22': 'Maquinaria de construcción',
  '23': 'Maquinaria de manufactura industrial',
  '24': 'Maquinaria de manejo de materiales',
  '25': 'Vehículos',
  '26': 'Generación de energía',
  '27': 'Herramientas y maquinaria general',
  '30': 'Componentes estructurales y de construcción',
  '31': 'Componentes de manufactura',
  '32': 'Componentes electrónicos',
  '39': 'Iluminación y componentes eléctricos',
  '40': 'Calefacción, ventilación y fluidos',
  '41': 'Equipo de laboratorio y medición',
  '42': 'Equipo médico',
  '43': 'Tecnología de información y telecomunicaciones',
  '44': 'Equipos y suministros de oficina',
  '45': 'Impresión, fotografía y audiovisuales',
  '46': 'Defensa, orden público y seguridad',
  '47': 'Limpieza',
  '48': 'Maquinaria para servicios',
  '49': 'Deportes y recreación',
  '50': 'Alimentos y bebidas',
  '51': 'Medicamentos',
  '52': 'Artículos domésticos',
  '53': 'Ropa y aseo personal',
  '54': 'Joyería y relojes',
  '55': 'Productos impresos y publicaciones',
  '56': 'Muebles y mobiliario',
  '60': 'Instrumentos musicales, juegos y educación',
  '70': 'Servicios agrícolas, pesqueros y forestales',
  '71': 'Servicios de minería, petróleo y gas',
  '72': 'Construcción e instalaciones',
  '73': 'Producción industrial y manufactura',
  '76': 'Limpieza industrial',
  '77': 'Servicios medioambientales',
  '78': 'Transporte, almacenaje y correo',
  '80': 'Servicios de gestión y profesionales',
  '81': 'Ingeniería, investigación y tecnología',
  '82': 'Editorial, diseño y artes gráficas',
  '83': 'Servicios públicos',
  '84': 'Servicios financieros y seguros',
  '85': 'Servicios de salud',
  '86': 'Educación y formación',
  '90': 'Viajes, alimentación y alojamiento',
  '91': 'Servicios personales y domésticos',
  '92': 'Defensa, seguridad y vigilancia',
  '93': 'Servicios políticos y cívicos',
  '94': 'Organizaciones y clubes',
  '95': 'Terrenos, edificios y vías',
};

export const UNSPSC_FAMILY_LABELS: Readonly<Record<string, string>> = {
  '4319': 'Dispositivos de comunicaciones',
  '4320': 'Componentes para TI y telecomunicaciones',
  '4321': 'Equipos de cómputo y accesorios',
  '4322': 'Equipos de redes y telecomunicaciones',
  '4323': 'Software',
  '8110': 'Servicios profesionales de ingeniería',
  '8111': 'Servicios informáticos',
  '8112': 'Servicios de economía',
  '8113': 'Estadística',
  '8114': 'Tecnologías de fabricación',
  '8115': 'Ciencias de la tierra',
  '8116': 'Servicios de tecnologías de información',
  '8010': 'Asesoría de gestión',
  '8011': 'Recursos humanos',
  '8012': 'Servicios legales',
  '8014': 'Comercialización y distribución',
  '8016': 'Administración empresarial',
  '8210': 'Publicidad',
  '8214': 'Diseño gráfico',
  '2315': 'Maquinaria de procesos industriales (incl. robots)',
  '4111': 'Instrumentos de laboratorio y medición',
};

/**
 * Affinity (0–1) of a UNSPSC family/segment with a solo software/robotics contractor.
 * Family takes precedence over segment; unknown segments get a neutral-low value.
 */
export const UNSPSC_FAMILY_AFFINITY: Readonly<Record<string, number>> = {
  '4323': 1,
  '8111': 1,
  '8116': 0.9,
  '2315': 0.6,
  '4321': 0.5,
  '4322': 0.5,
  '8110': 0.5,
  '8114': 0.5,
  '4320': 0.4,
  '4319': 0.4,
  '4111': 0.4,
  '8010': 0.35,
  '8113': 0.3,
  '8014': 0.3,
  '8016': 0.3,
  '8214': 0.3,
  '8615': 0.2,
};

export const UNSPSC_SEGMENT_AFFINITY: Readonly<Record<string, number>> = {
  '43': 0.5,
  '81': 0.4,
  '80': 0.25,
  '32': 0.2,
  '41': 0.2,
  '45': 0.15,
  '82': 0.15,
  '86': 0.15,
  '23': 0.15,
  '24': 0.1,
};

export const UNSPSC_UNKNOWN_AFFINITY = 0.3;
export const UNSPSC_UNRELATED_AFFINITY = 0;
